apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.8.3-openjdk-17
      command:
        - cat
      tty: true
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2
    - name: docker
      image: 'docker:latest'
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: maven-repo
      hostPath:
        path: /var/maven
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock